project_id = "gfjsvuoqaheiaddvfrwb"

[functions.pix-api]
verify_jwt = false

[functions.clear-test-data]
verify_jwt = false

[functions.send-member-access-email]
verify_jwt = true

[functions.generate-fee-pix]
verify_jwt = true

[functions.fee-webhook]
verify_jwt = false

[functions.send-fee-reminder]
verify_jwt = true

[functions.auto-block-sellers]
verify_jwt = true

[functions.send-pix-notification]
verify_jwt = false

[functions.send-payment-confirmed]
verify_jwt = false

[functions.process-sales-recovery]
verify_jwt = false

[functions.allow-domain]
verify_jwt = false

[functions.send-withdrawal-notification]
verify_jwt = false

[functions.generate-instagram-post]
verify_jwt = true

[functions.whatsapp-broadcast]
verify_jwt = true

[functions.check-scheduled-broadcasts]
verify_jwt = false

[functions.continue-running-broadcasts]
verify_jwt = false

[functions.email-broadcast]
verify_jwt = true

[functions.continue-email-broadcasts]
verify_jwt = false

[functions.check-scheduled-email-broadcasts]
verify_jwt = false

[functions.get-gateway-credentials]
verify_jwt = true

[functions.external-payment-api]
verify_jwt = false

[functions.create-tenant-admin]
verify_jwt = false

[functions.process-gateflow-sale]
verify_jwt = false

[functions.mark-as-paid]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.backfill-gateflow-buyers]
verify_jwt = true

[functions.grant-member-access]
verify_jwt = false

[functions.update-customer-email]
verify_jwt = false

[functions.backfill-order-bump-memberships]
verify_jwt = true
