project_id = "gfjsvuoqaheiaddvfrwb"

[functions.pix-api]
verify_jwt = false

[functions.clear-test-data]
verify_jwt = false

[functions.send-member-access-email]
verify_jwt = true

[functions.generate-fee-pix]
verify_jwt = true

[functions.fee-webhook]
verify_jwt = false

[functions.send-fee-reminder]
verify_jwt = true

[functions.auto-block-sellers]
verify_jwt = true
